//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "api_user_access")]
#[serde(rename_all = "snake_case")]
pub enum ApiUserAccess {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "delete")]
    Delete,
    #[sea_orm(string_value = "read")]
    Read,
    #[sea_orm(string_value = "write")]
    Write,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "api_user_role")]
#[serde(rename_all = "snake_case")]
pub enum ApiUserRole {
    #[sea_orm(string_value = "client_admin")]
    ClientAdmin,
    #[sea_orm(string_value = "realm_admin")]
    RealmAdmin,
}
